"""empty message

Revision ID: 41d31dade3d0
Revises: 
Create Date: 2022-04-07 01:59:00.754226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d31dade3d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'free',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'free',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
