"""empty message

Revision ID: 79186b5cb5c7
Revises: 41d31dade3d0
Create Date: 2022-04-07 21:13:31.191696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79186b5cb5c7'
down_revision = '41d31dade3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'client_phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'client_phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
